main: phonon.xc.XCPlugin
name: xc
version: 0.0.4
api-version: 1.16
softdepend: [WorldGuard]
commands:
  xc:
    description: xc
    aliases: []
    permission: xc.command
    usage: /xc help
  aimdownsights:
    description: Toggles gun aim down sights
    aliases: [ads]
    permission: xc.ads
    usage: /ads off
permissions:
  xc.admin:
    description: Allow xc admin commands
    default: op

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0
  - org.jetbrains.kotlin:kotlin-reflect:2.2.0
  - org.tomlj:tomlj:1.1.1