# THIS IS A GENERATED COMPONENT CONFIG EXAMPLE FILE THAT SHOWS
# THIS COMPONENT'S CONFIG OPTIONS.



[ammo]

current = 0
max = 40

# val type: Ammo? = null, # TODO: load from xc combat plugin
# drop fuel item instead of storing into item during despawn
drop_item = true