# THIS IS A GENERATED COMPONENT CONFIG EXAMPLE FILE THAT SHOWS
# THIS COMPONENT'S CONFIG OPTIONS.

# Health and death component

[health]

current = -1.0
max = 20.0

# damage sources multipliers
enum_array_map<_damage_type = EnumArrayMap.from(