# XC Config
# Combat plugin for miney man

# folders within `plugins/xc` containing item configs
[configs]
ammo = "ammo"
armor = "armor"
gun = "gun"
melee = "melee"
misc = "misc"
throwable = "throwable"

# max number of ticks from last auto fire request before stopping
[auto_fire]
max_ticks_since_last_request = 4

# recoil recovery rate per tick
[recoil]
recovery_rate = 0.2

# block damage
[block_damage]
explosion = false

# material types for custom items, must match a Material exactly
[material]
gun = "WARPED_FUNGUS_ON_A_STICK"
aim_down_sights = "CARROT_ON_A_STICK"
melee = "IRON_SWORD"
throwable = "GOLDEN_HORSE_ARMOR"
ammo = "SNOWBALL"
armor = "LEATHER_HORSE_ARMOR"

# ADVANCED ENGINE CONFIG
# generally dont touch these...

# sway config
[sway]
players_before_pipelined_sway = 4

# crawl config
[crawl]
only_allowed_on_crawl_weapons = true

# debug stuff
[debug]
do_timings_default = false # default state for whether to do debug timings

# experimental stuff
[experimental]
async_packets = true # sends most packets using an async task