# XC Config
# Combat plugin for miney man

# folders within `plugins/xc` containing item configs
[configs]
gun = "gun"
ammo = "ammo"
melee = "melee"
misc = "misc"
armor = "armor"

# block damage
[block_damage]
explosion = false

# ADVANCED ENGINE CONFIG
# generally dont touch these...

# material types for custom items, must match a Material exactly
[material]
gun = "WARPED_FUNGUS_ON_A_STICK"
melee = "IRON_HORSE_ARMOR"
misc = "GOLDEN_HORSE_ARMOR"
armor = "LEATHER_HORSE_ARMOR"
