main: phonon.xv.XVPlugin
name: xv
version: 0.0
api-version: 1.16
depend: [kotlin, ProtocolLib]
softdepend: [xc]
commands:
  xv:
    description: xv
    permission: xv.command
    usage: /xv help
  vehicledecal:
    aliases: [vdecal]
    permission: xv.vehicledecal
    usage: /vehicledecal [name]
  vehicleskin:
    aliases: [vskin]
    permission: xv.vehicleskin
    usage: /vehicleskin [name]
permissions:
  xv.admin:
    description: Allow xv admin commands
    default: op