# THIS IS A GENERATED COMPONENT CONFIG EXAMPLE FILE THAT SHOWS
# THIS COMPONENT'S CONFIG OPTIONS.

# Mouse-controlled rotating gun turret.
# 
# Component made from two armor stands:
# - Turret: yaw (y-plane) rotation only
# - Barrel: up/down rotation only in-plane,
#           forward direction = turret yaw
# 
# Contains LOCAL position/rotation offsets from base element transform.
# Controls system functions should always use this in combination
# with a TransformComponent as the base transform position.
# 
# This also internally manages rendering armor stand models
# for turret and barrel

[gun_turret]

# turret local offset relative to transform
turret_offset = [0.0, 1.0, 0.0]

# barrel local offset relative to transform (NOT turret)
barrel_offset = [0.0, 1.0, 0.0]

# min turret pitch rotation (in degs)
turret_pitch_min = -15.0

# max turret pitch rotation (in degs)
turret_pitch_max = 15.0

# min barrel pitch rotation (in degs)
barrel_pitch_min = -15.0

# max barrel pitch rotation (in degs)
barrel_pitch_max = 15.0

# max turret yaw rotation half-arc relative to transform, only used if >0 (in degs)
turret_yaw_half_arc = 0.0

# max barrel yaw rotation half-arc relative to turret, only used if >0 (in degs)
barrel_yaw_half_arc = 0.0

# control style for turret yaw (mouse, wasd, or none)
turret_control_yaw = "NONE"

# control style for barrel yaw (mouse, wasd, or none)
barrel_control_yaw = "NONE"

# control style for barrel pitch (mouse, wasd, or none)
barrel_control_pitch = "NONE"

# speed that turret yaw rotates at
turret_yaw_rotation_speed = 1.0

# speed that barrel yaw rotates at
barrel_yaw_rotation_speed = 1.0

# speed that barrel pitch rotates at
barrel_pitch_rotation_speed = 0.5

# seat index that controls this component
seat_controller = 0

# seat to mount when armorstand clicked, -1 for none
seat_to_mount = -1

# if true, turret yaw will also update base transform yaw
update_transform = false

# material for model
material = "BONE"

# custom model data for the armorstands
turret_model_id = 0
barrel_model_id = 0

# name of skins variant set to use instead of single model id (optional)
skin_turret = null
skin_turret_default_variant = null
skin_barrel = null
skin_barrel_default_variant = null

# whether to show the armor stand (for debugging)
# hitbox size in blocks, at local position
hitbox = [1.0, 1.0, 1.0]
hitbox_y_offset = 0.0

# if can shoot with left mouse, which ammo group to shoot (-1 to disable)
shoot_mouse_weapon = 0

# if can shoot with spacebar, which ammo group to shoot (-1 to disable)
shoot_spacebar_weapon = -1

# offset along barrel direction to spawn projectile
projectile_offset = 1.0