# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_cannon"

item_name = "Debug Cannon"
item_custom_model_data = 100000
item_lore = [
    "This is a debug cannon.",
]

spawn_time = 2.0
despawn_time = 2.0

# contains position, rotation, etc.
[transform]

# apply gravity so vehicle falls
# NOTE: due to minecraft client side interpolation, sometimes
# vehicle will appear to fall into ground. but after relogging, it
# will properly be on top of block again...
[gravity]
area = 1
delay = 1

# rotating gun barrel model
# moves up/down with WASD controls
[gun_turret]
turret_offset = [0.0, 0.0, 0.0]
barrel_offset = [0.0, -0.35, 0.0]
barrel_pitch_min = -30.0
barrel_pitch_max = 45.0
barrel_pitch_rotation_speed = 1.0
turret_control_yaw = "wasd"
barrel_control_yaw = "wasd"
barrel_control_pitch = "wasd"
turret_model_id = 100001
barrel_model_id = 100002
seat_to_mount = 0 # seat mounted when clicked
seat_controller = 0 # seat for controlling vehicle
update_transform = true
shoot_mouse_weapon = 0 # which ammo group to shoot
hitbox = [1.4, 1.4, 1.4]
hitbox_y_offset = 0.0
shoot_offset_y = 1.0

# seats, needed for controllable vehicle
[seats]
seats = [
    { offset = [0.0, 0.2, -1.0], armor = 2.0 },
]

# health needed so you can shoot cannons with cannons or guns
[health]
max = 20.0
death_sound = "minecraft:entity.generic.explode"
death_particle = "EXPLOSION_NORMAL"
death_particle_count = 8
death_particle_random_x = 0.5
death_particle_random_y = 0.75
death_particle_random_z = 0.5

[health.damage_multiplier]
ANTI_TANK_RIFLE = 0.5
ARMOR_PIERCING = 1.0
ARMOR_PIERCING_SHELL = 1.0
EXPLOSIVE = 0.75
EXPLOSIVE_SHELL = 1.0
MOLOTOV = 1.0

# ammos and their associated guns
[ammo]
can_reload_inside = false # disable reloading while sitting
can_reload_outside = true
time_reload_outside = 2000 # milliseconds
groups = [
    { max_ammo = 1 }, # group 0
]
# demo allowing multiple ammo and gun types in cannon
types = [
    { group = 0, ammo = 400, gun = 900 }, # explosive round shot
    { group = 0, ammo = 401, gun = 901 }, # grapeshot (like shotgun)
]
