# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_ship"

item_name = "Debug Ship"
item_custom_model_data = 116000
item_lore = []

spawn_time = 2.0
despawn_time = 2.0

# contains position, rotation, etc.
[transform]

# armor stand model
[model]
model_id = 116000

# seats, needed for controllable vehicle
[seats]
seats = [
    { offset = [0.0, 0.4, 0.6], armor = 4.0 },
    { offset = [0.0, 0.4, -0.6], armor = 4.0 },
    { offset = [0.0, 0.4, -3.0], armor = 4.0 },
]


# use seat raycasting for mounting
[seats_raycast]
hitbox_width = 0.75
hitbox_height = 1.0
hitbox_height_offset = -0.25

# handles player's input controls for ship movement
[ship_movement_controls]
# seat index that controls vehicle
seat_controller = 0

# translational speed parameters (all positive)
acceleration = 0.02
deceleration_multiplier = 0.8
speed_max_forward = 0.4
speed_max_reverse = 0.3

# yaw turning rate parameters
yaw_rotation_acceleration = 0.1
yaw_rotation_deceleration_multiplier = 0.5
yaw_rotation_speed_max = 2.0

# the speed at which boats can
# turn at the full turn accel
yaw_rotation_effective_speed = 0.1

# collision settings
# i-frame after collision, -1 to disable
collision_cooldown_ticks = 60

# min speed needed to register a collision, -1 to disable
min_collision_speed = 0.2

# contact points for gravity
ground_contact_points = [
    1.2, 0.0, 2.0,
    -1.2, 0.0, 2.0,
    1.2, 0.0, -2.0,
    -1.2, 0.0, -2.0,
]
front_contact_points = [
    1.2, 0.0, 2.0,
    -1.2, 0.0, 2.0,
    1.2, 3.0, 2.0,
    -1.2, 3.0, 2.0,
    0.0, 1.5, 2.0,
]
backward_contacts_displace = [
    0.0,
    0.0,
    -4.0
]

[health]
max = 20.0
death_sound = "minecraft:entity.generic.explode"
death_particle = "EXPLOSION_HUGE"
death_particle_count = 1

[health.damage_multiplier]
BULLET = 0.1
ANTI_TANK_RIFLE = 0.5
ARMOR_PIERCING = 1.0
ARMOR_PIERCING_SHELL = 1.0
EXPLOSIVE = 0.25
EXPLOSIVE_SHELL = 0.5
MOLOTOV = 1.0
FLAK = 1.0

# smoke particles from boat smoke stack
# TODO: fix smoke particle offsets
[smoke_particles]
particle = "CAMPFIRE_COSY_SMOKE"
offset_x = 0.0
offset_y = 3.0
offset_z = -2.5
random_x = 0.25
random_y = 0.3
random_z = 0.25
speed = 0.22
extra_data = 0.22
health_threshold = 20.0
tick_period = 3
