# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_humvee"

# contains position, rotation, etc.
[transform]

# armor stand model
[model]
model_id = 103001

# rotating gun turret, controlled by mouse
[gun_turret]
turret_offset = [0.0, 1.75, 0.75]
barrel_offset = [0.0, 0.1, 0.0]
barrel_pitch_min = -15.0
barrel_pitch_max = 15.0
turret_control_yaw = "mouse"
barrel_control_yaw = "mouse"
barrel_control_pitch = "mouse"
turret_model_id = 103002
barrel_model_id = 103003
seat_controller = 4 # seat for controlling gun turret

# seats, needed for controllable vehicle
# seats, needed for controllable vehicle
[seats]
seats = [
    { offset = [ 0.9, 0.9,  0.0], armor = 8.0 }, # front left (driver)
    { offset = [-0.9, 0.9,  0.0], armor = 8.0 }, # front right
    { offset = [ 0.9, 0.9, -1.0], armor = 8.0 }, # back left
    { offset = [-0.9, 0.9, -1.0], armor = 8.0 }, # back right
    { offset = [ 0.0, 2.5,  0.0], armor = 8.0 }, # gunner
]

# seat raycasting for mounting
# TODO: should be removed, only here for testing because
# only 1 archetype layout supported
[seats_raycast]

# handles player's input controls for land movement
[land_movement_controls]
seat_controller = 0
acceleration = 0.03
speed_max_forward = 0.3
speed_max_reverse = 0.2
