# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_cannon"

# contains position, rotation, etc.
[transform]

# base model
[model]
barrel_offset = [0.0, -0.25, 0.0]
model_id = 100001
seat_to_mount = 0 # seat mounted when clicked

# rotating gun barrel model
# moves up/down with WASD controls
[gun_barrel]
barrel_offset = [0.0, -0.4, 0.0]
barrel_pitch_min = -15.0
barrel_pitch_max = 15.0
control_yaw_wasd = true
control_pitch_wasd = true
update_transform = true
seat_to_mount = 0 # seat mounted when clicked
model_id = 100002

# seats, needed for controllable vehicle
[seats]
count = 1
offsets = [0.0, -1.0, -1.0]
