# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_mortar"

# contains position, rotation, etc.
[transform]

# armor stand gun barrel
[gun_barrel]
barrel_offset = [0.0, -0.75, 0.0]
barrel_pitch_min = -15.0
barrel_pitch_max = 45.0
model_id = 101000
seat_to_mount = 0 # seat mounted when clicked

# seats, needed for controllable vehicle
[seats]
count = 1
offsets = [0.0, -1.6, -0.75]