# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_car"

item_name = "Debug Car"
item_lore = [
    "This is a debug car.",
]

# contains position, rotation, etc.
[transform]

# armor stand model
[model]
model_id = 102000

# seats, needed for controllable vehicle
[seats]
count = 4
offsets = [
    0.9, -0.5, 0.0,   # front left
    -0.9, -0.5, 0.0,  # front right
    0.9, -0.5, -1.0,  # back left
    -0.9, -0.5, -1.0, # back right
]

# use seat raycasting for mounting
[seats_raycast]

# handles player's input controls for land movement
[land_movement_controls]
seat_controller = 0
acceleration = 0.05
speed_max_forward = 0.4
speed_max_reverse = 0.3
