# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_mortar"
spawn_time = 2.0
despawn_time = 2.0

# contains position, rotation, etc.
[transform]

# armor stand gun barrel
[gun_barrel]
barrel_offset = [0.0, -0.75, 0.0]
pitch_min = -20.0
pitch_max = 20.0
pitch_rotation_speed = 0.2
control_yaw = "mouse"
control_pitch = "wasd"
update_transform = true
seat_to_mount = 0 # seat mounted when clicked
model_id = 101000

# seats, needed for controllable vehicle
[seats]
count = 1
offsets = [0.0, -1.6, -0.75]