# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

name = "debug_tank"

item_name = "Debug Tank"
item_lore = [
    "Tanks when",
]

# contains position, rotation, etc.
[transform]

# armor stand model
[model]
model_id = 104001
seat_to_mount = 0 # seat mounted when clicked
hitbox = [2.5, 2.5, 2.5]

# rotating gun turret, controlled by mouse
[gun_turret]
turret_offset = [0.0, 0.5, 0.0]
barrel_offset = [0.0, 0.5, 2.0]
barrel_pitch_min = -15.0
barrel_pitch_max = 15.0
turret_control_yaw = "mouse"
barrel_control_yaw = "mouse"
barrel_control_pitch = "mouse"
turret_model_id = 104002
barrel_model_id = 104003
seat_to_mount = 0 # seat mounted when clicked
seat_controller = 0 # seat for controlling gun

# seats, needed for controllable vehicle
[seats]
count = 1
offsets = [
    0.0, 1.8, 0.0,
]
armor = [ 9001.0 ]

# handles player's input controls for land movement
[land_movement_controls]
seat_controller = 0
acceleration = 0.03
speed_max_forward = 0.3
speed_max_reverse = 0.2

[health]
max_health = 40.0
death_sound = "minecraft:entity.generic.explode"
death_particle = "EXPLOSION_HUGE"
death_particle_count = 1

[fuel]
max = 64
material = "DRAGON_BREATH"
amount_per_item = 1
max_amount_per_refuel = 32
time_per_fuel_when_idle = 200
time_per_fuel_when_moving = 60

# smoke particles when health < 50%
[smoke_particles]
particle = "CAMPFIRE_COSY_SMOKE"
offset_x = 0.0
offset_y = 1.0
offset_z = 0.0
random_x = 0.75
random_y = 0.4
random_z = 0.75
speed = 0.22
extra_data = 0.22
health_threshold = 10.0
tick_period = 4

# lava particles when health < 25%
[particles]
particle = "LAVA"
count = 4
offset_x = 0.0
offset_y = 1.0
offset_z = 0.0
random_x = 0.3
random_y = 1.0
random_z = 0.3
health_threshold = 5.0
tick_period = 2