# Simple vehicles do not have any duplicate components so
# these only need a single element. In this case, we can
# just write components directly in the config.
# Parser will do a scan and recognize this only needs a
# single anonymous element.

# maschinengewehr 34 ("machine gun 34")
name = "debug_mg34"

# contains position, rotation, etc.
[transform]

# armor stand gun barrel
[gun_barrel]
barrel_offset = [0.0, -0.75, 0.0]
pitch_min = -30.0
pitch_max = 30.0
pitch_rotation_speed = 0.2
control_yaw = "mouse"
control_pitch = "mouse"
update_transform = true
seat_to_mount = 0 # seat mounted when clicked
model_id = 106000

# seats, needed for controllable vehicle
[seats]
count = 1
offsets = [0.0, -1.75, -1.0]