# Gun id. Used to map different custom models => gun.
# Must be an integer from [0, 1024].
id = 930

# Item properties
[item]
name = "&6Fighter Plane"
lore = []

# SPECIAL VEHICLE WEAPON:
# only need default (sets gun id), set all others to -1
[model]
default = 930
empty = -1
reload = -1
ads = -1

# Equiped properties
[equip]
delay = 1000
slowness = 0
no_sprint = false

# Crawl required
[crawl]
required = false
time = 1000

# Ammo id and count
[ammo]
id = 30
desc = ".50 Cal Machinegun"
max = 20
per_reload = -1
ignore = false

# Reload time in milliseconds
[reload]
time = 2500

# [left-click] Single or burst mode firing config
[shoot]
fire_mode = "burst"
burst_count = 3
burst_delay = [2, 1]
delay = 300

# [right-click] Automatic fire settings
[automatic]
enabled = true
delay_ticks = [2, 2, 2, 1]
slowness = 1

# sway: projectile randomness depending on player motion state
[sway]
base = 0.030
speed_multiplier = 0.100
aim_down_sights = 0.250
ride_horse = 1.500
ride_boat = 1.500
ride_armor_stand = 1.000

# player visual recoil from firing guns
[recoil]
single_horizontal = 2.000
single_vertical = 4.000
auto_horizontal = 2.000
auto_vertical = 4.000
single_fire_ramp = 0.100
auto_fire_ramp = 0.100

# Handler for what happens when projectile hits a block or entity.
# If nothing specified, no effect will happen when a projectile hits.
# Events will still be emitted, allowing custom handlers to be used.
# So disable these if you are managing hits in external plugin.
# Valid options for entity: ["damage", "explosion"]
# Valid options for block: ["explosion"]
[hit]
entity = "damage"
fire_ticks = 0
block_fire_probability = 0.000

# Projectile properties.
# Damage types:
# ["UNKNOWN", "MELEE", "BULLET", "FIRE", "EXPLOSIVE", "EXPLOSIVE_SHELL", "ARMOR_PIERCING", "ARMOR_PIERCING_SHELL"]
[projectile]
count = 1
damage = 13.0
armor_reduction = 0.500
resist_reduction = 0.500
velocity = 20.000
gravity = 0.025
lifetime = 100
max_distance = 120.000
damage_type = "BULLET"
damage_min = 13.000
damage_drop_distance = 0.0

# projectile particle trail properties
[projectile.particles]
type = "REDSTONE"
size = 1.5
color = [255, 255, 255]
spacing = 1.500
force_render = true
block_hit_particles = true

# Explosion damage properties. These are only used if the handler
# for block or entity hit has an explosion effect.
[explosion]
damage = 0.000
max_distance = 8.000
radius = 2.000
falloff = 2.000
armor_reduction = 0.500
blast_prot_reduction = 0.500
damage_type = "BULLET"
block_damage_power = 0.000

# Explosion particle settings
[explosion.particles]
type = "EXPLOSION_LARGE"
count = 8
random_x = 0.500
random_y = 0.500
random_z = 0.500

# Sounds
[sound]
shoot = "smg_bar1918.shoot"
empty = "smg_bar1918.empty"
reload_start = "smg_bar1918.reload_start"
reload_finish = "smg_bar1918.reload_finish"
# alternative detailed mode to specify volume and pitch
# shoot = { name = "gun_shoot", volume = 1.0, pitch = 1.0 } 
# empty = { name = "gun_empty", volume = 1.0, pitch = 1.0 } 
# reload_start = { name = "gun_reload_start", volume = 1.0, pitch = 1.0 } 
# reload_finish = { name = "gun_reload_finish", volume = 1.0, pitch = 1.0 } 