# Debugging ammo, shows all configurable properties.
# For testing/loading ammo properties.

# Ammo id. This is the ammo custom model data.
id = 405

# Item properties
[item]
name = "Mortar Shell"
lore = [
    "Exploding shell fired by mortar.",
]