# Debugging ammo, shows all configurable properties.
# For testing/loading ammo properties.

# Ammo id. This is the ammo custom model data.
id = 401

# Item properties
[item]
name = "Cannon Grape Shot"
lore = [
    "Short range anti-infantry cluster shot.",
]